### ISSUE TITLE
False face detection

### ISSUE THREAD

**Issue by koliapp2019** [fcakyon/face-detection-app-tutorial#3]
![image](https://user-images.githubusercontent.com/55689661/112079202-b3b39200-8bba-11eb-95ea-3e80e8a8b586.png)

![image](https://user-images.githubusercontent.com/55689661/112079347-f70e0080-8bba-11eb-817b-db01d05fb606.png)

![image](https://user-images.githubusercontent.com/55689661/112079382-042aef80-8bbb-11eb-8495-d3a157c32ef4.png)

![image](https://user-images.githubusercontent.com/55689661/112079772-b6fb4d80-8bbb-11eb-9581-8fe554ed3232.png)

Could you check why these photos falsely detected the extra face(s)? Some of them the confidence index is quite high. Thanks!

**Comment by koliapp2019** [comment]
For this photo 
![image](https://user-images.githubusercontent.com/55689661/112089918-82908d00-8bcd-11eb-8773-f555d0b15d96.png), it even said that there were7 faces. Not sure why, look like only 2 were detected but the count said 7.

**Comment by koliapp2019** [comment]
![lark](https://user-images.githubusercontent.com/55689661/112090113-e9ae4180-8bcd-11eb-8781-fb00a0058b89.PNG)

Attached the original.

**Comment by fcakyon** [comment]
You can increase the detection threshold in [config](https://github.com/fcakyon/face-detection-app-tutorial/blob/879c1795e26bdf53e1e23d8f8587625936aa3bf7/config.py#L1) to 0.6 or 0.7.

SSD based face detector that I used is not the best performing one, false positives are result of that, it is not a bug but expected behaviour.

**Comment by fcakyon** [comment]
@koliapp2019 I will add support to a better face detector model when I find some time, keep an eye on the related issue for updates: https://github.com/fcakyon/face-detection-app-tutorial/issues/4

**Comment by koliapp2019** [comment]
Actually changing the values higher makes it worse. Just FYI. Will just stick with 0.2.
